feat: 阅读建议
AirboZH/halo-theme-chirpy pull request #82
Opened 2023-09-14 18:10 UTC by waite0603

Resolves https://github.com/AirboZH/halo-theme-chirpy/issues/26#issue-1867985218 and https://github.com/AirboZH/halo-theme-chirpy/issues/27#issue-1867985246

![image](https://github.com/AirboZH/halo-theme-chirpy/assets/75354124/ed91b89d-5834-4abc-a00a-92f2ded3a93e)

2023-09-14 21:30 UTC, AirboZH commented
> 他有个问题就是 API 中`文章摘要`好像只有手动输入的时候才能拿到! 
> ![image](https://github.com/AirboZH/halo-theme-chirpy/assets/75354124/89e0a3cb-11c4-486d-a788-ccf8d0f96829)
> 
> 

参考#6，使用 `status.excerpt`

2023-09-14 21:36 UTC, AirboZH reviewed
lgtm,
待我安装测试后合并

2023-09-14 21:37 UTC, AirboZH requested changes

2023-09-14 21:37 UTC, AirboZH commented on templates/modules/post/relatedPosts.html
> +                <p th:text="${recommendPost.spec.excerpt.raw}"></p>
```suggestion
                <p th:text="${recommendPost.status.excerpt}"></p>
```

2023-09-15 01:54 UTC, AirboZH commented
原版这个地方应该是div而且有disable的class
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/6bf4de04-b1f9-4856-aed9-ad252f32b1d9)
咱们这个地方在没有文章的地方还能点下去
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/0a86ec0a-2122-42fb-93f8-e0eaae43b1e6)

可以麻烦你再改进一下么

2023-09-15 01:55 UTC, AirboZH commented
而且这两个按钮似乎反了，older是更新的，newer是更旧的

2023-09-15 05:43 UTC, AirboZH approved these changes

2023-09-15 05:43 UTC, merged

2023-09-15 06:06 UTC, waite0603 commented on templates/modules/post/relatedPosts.html
> +    </a>
> 可以判断`postCursor.next`是否为空 为空则为
> 
> ```
>   <div
>     class="btn btn-outline-primary disabled"
>     prompt="{{ site.data.locales[include.lang].post.button.previous }}"
>   >
>     <p>-</p>
>   </div>
> ```
> 
> 参考https://github.com/AirboZH/halo-theme-chirpy/blob/master/src/_layouts/_includes/post-nav.html

我刚看了以下 Halo   {% if postCursor.next == null %} {% else %} 好像渲染不出来, 会直接渲染成 Html
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/75354124/3535d57d-c6f6-432a-8c7f-7a01c37053f2)
现在这种写法和原版目前按=效果基本相似
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/75354124/a61aa95b-67f7-4c88-a8be-f756deddda76)

2023-09-15 06:08 UTC, AirboZH commented on templates/modules/post/relatedPosts.html
> +    </a>
是的，原版主题是[Jekyll](https://jekyllrb.com/)的语法。
那就这样吧，问题不大

感谢贡献